[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; La cámara necesita PSRAM habilitada (la Sense la trae en el módulo)
board_build.arduino.memory_type = qio_opi
board_build.psram = enable

monitor_speed = 115200

; Subida normal por USB-serial (no confundir con el debug por JTAG)
upload_protocol = esptool

; Debug SÍ usa el JTAG nativo del S3 (solo aplica cuando le das a "Debug", no a "Upload")
debug_tool = esp-builtin

; esp32-camera ya viene incluida en el core de Arduino-ESP32,
; no hace falta agregarla como lib_deps aparte.
build_flags =
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_XIAO_ESP32S35